<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>QuatiTimeWebApi</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="2.2.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.0" />
    <PackageReference Include="ErrorOr" Version="2.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../QuatiTime/PortalHorasApi/PortalHorasApi.csproj" />
  </ItemGroup>

</Project>
